#!/bin/sh

GIVEN_INPUT_FILEPATH=$1

while getopts "f:o:" opt; do
  case $opt in
    f) FORMAT=$OPTARG;;                # format
    o) GIVEN_OUTPUT_FILEPATH=$OPTARG;; # output
    *) echo "Unknown option: $opt"; exit 1;;
  esac
done

INPUT_FILEPATH=$(realpath "$GIVEN_INPUT_FILEPATH")
INPUT_FILENAME=$(basename "$INPUT_FILEPATH" ".md")

if [ -z "$FORMAT" ]; then
  FORMAT="html"
fi

if [ -z "$GIVEN_OUTPUT_FILEPATH" ]; then
  OUTPUT_FILEPATH="$(pwd)/$INPUT_FILENAME.$FORMAT"
else
  OUTPUT_FILEPATH="$GIVEN_OUTPUT_FILEPATH"
fi

cd "$TYPESETTER_PATH/build" || exit 1

if [ "$FORMAT" = "html" ]; then
  echo "> HTML"
  node index.js "$INPUT_FILEPATH" "$OUTPUT_FILEPATH"
elif [ "$FORMAT" = "pdf" ]; then
  echo "> PDF"
  mkdir -p tmp
  node index.js "$INPUT_FILEPATH" "tmp/$INPUT_FILENAME.tmp.html"
  wkhtmltopdf -L 26 -R 26 -T 26 -B 26 "tmp/$INPUT_FILENAME.tmp.html" "$OUTPUT_FILEPATH"
  rm -f "tmp/$INPUT_FILENAME.tmp.html"
else
  echo "Unknown format: $FORMAT"
fi
